### ISSUE TITLE
pretrained

### ISSUE THREAD

**Issue by mengsiwei** [PinJui/FDRL#1]
您好，请问可以提供一下pretrained的model吗，readme里面的链接失效了

**Comment by PinJui** [comment]
Hello, please try the link provided by [EfficientFace](https://github.com/zengqunzhao/EfficientFace): [Pretrained ResNet18](https://drive.google.com/file/d/1dPCWFaa9xrs6nTVkweTJWyx9qGGdi3qe/view?usp=sharing). Thank you !

**Comment by mengsiwei** [comment]
thanks !
















At 2022-10-09 17:08:00, "PinJui" ***@***.***> wrote:

Hello, please try the link provided by EfficientFace: Pretrained ResNet18. Thank you !
